# Generated by Django 2.1.7 on 2019-03-29 20:47

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import django_countries.fields
import djmoney.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='name of account')),
                ('currency', models.CharField(choices=[('EUR', 'Euro'), ('USD', 'US Dollar')], default='EUR', max_length=3, verbose_name='Currency')),
                ('active', models.BooleanField(default=True, verbose_name='Active account')),
                ('owner', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AccountValuation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, verbose_name='Valuation date')),
                ('cur_value_currency', djmoney.models.fields.CurrencyField(choices=[('EUR', 'Euro'), ('USD', 'US Dollar')], default='EUR', editable=False, max_length=3)),
                ('cur_value', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0.0'), default_currency='EUR', max_digits=10, verbose_name='Current value')),
                ('base_value_currency', djmoney.models.fields.CurrencyField(choices=[('EUR', 'Euro'), ('USD', 'US Dollar')], default='EUR', editable=False, max_length=3)),
                ('base_value', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0.0'), default_currency='EUR', max_digits=10, verbose_name='Base value based on in- and outflows')),
                ('modifiedDate', models.DateField(db_index=True, verbose_name='Last modification')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='returns.Account')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExchangeUSDToEUR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Exchange date')),
                ('USDperEUR', models.DecimalField(decimal_places=5, max_digits=7, verbose_name='Exchange rate (USD/EUR)')),
            ],
        ),
        migrations.CreateModel(
            name='HistValuation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, verbose_name='Valuation date')),
                ('value_currency', djmoney.models.fields.CurrencyField(choices=[('EUR', 'Euro'), ('USD', 'US Dollar')], default='EUR', editable=False, max_length=3)),
                ('value', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0.0'), default_currency='EUR', max_digits=10, verbose_name='Valuation')),
            ],
        ),
        migrations.CreateModel(
            name='Inflation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Inflation date')),
                ('inflationIndex', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Inflation index')),
                ('country', django_countries.fields.CountryField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Security',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='name of security')),
                ('descrip', models.CharField(max_length=400, verbose_name='detailed description')),
                ('url', models.URLField(blank=True, default='', max_length=400, verbose_name='URL for pricing info')),
                ('symbol', models.CharField(blank=True, default='', max_length=10, verbose_name='Security symbol for pricing lookup')),
                ('kind', models.CharField(choices=[('TG', 'Savings'), ('AK', 'Stock'), ('AF', 'Stock-ETF'), ('BF', 'Bond-ETF'), ('BD', 'Bond'), ('AV', 'Retirement')], default='AF', max_length=2, verbose_name='kind of security')),
                ('mark_to_market', models.BooleanField(default=False, verbose_name='True if security priced to market')),
                ('accumulate_interest', models.BooleanField(default=False, verbose_name='True if interest accumulates (e.g. savings accounts)')),
                ('calc_interest', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Fixed interest rate (%)')),
                ('currency', models.CharField(choices=[('EUR', 'Euro'), ('USD', 'US Dollar')], default='EUR', max_length=3, verbose_name='Currency')),
                ('active', models.BooleanField(default=True, verbose_name='Active security')),
            ],
            options={
                'verbose_name_plural': 'Securities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SecurityValuation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, verbose_name='Valuation date')),
                ('cur_value_currency', djmoney.models.fields.CurrencyField(choices=[('EUR', 'Euro'), ('USD', 'US Dollar')], default='EUR', editable=False, max_length=3)),
                ('cur_value', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0.0'), default_currency='EUR', max_digits=10, verbose_name='Current value')),
                ('base_value_currency', djmoney.models.fields.CurrencyField(choices=[('EUR', 'Euro'), ('USD', 'US Dollar')], default='EUR', editable=False, max_length=3)),
                ('base_value', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0.0'), default_currency='EUR', max_digits=10, verbose_name='Base value based on in- and outflows')),
                ('modifiedDate', models.DateField(db_index=True, verbose_name='Last modification')),
                ('sum_num', models.DecimalField(decimal_places=5, default=0, max_digits=13, verbose_name='sum of number of securities exchanged')),
                ('owner', models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('security', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='returns.Security')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, verbose_name='transaction date')),
                ('kind', models.CharField(choices=[('SE', 'Sell'), ('BU', 'Buy'), ('IN', 'Interest'), ('DI', 'Dividend'), ('MA', 'Company Match'), ('WD', 'Write Down')], default='SE', max_length=2, verbose_name='kind of transaction')),
                ('expense_currency', djmoney.models.fields.CurrencyField(choices=[('EUR', 'Euro'), ('USD', 'US Dollar')], default='EUR', editable=False, max_length=3)),
                ('expense', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='EUR', max_digits=10, verbose_name='expenses allocated to transaction')),
                ('tax_currency', djmoney.models.fields.CurrencyField(choices=[('EUR', 'Euro'), ('USD', 'US Dollar')], default='EUR', editable=False, max_length=3)),
                ('tax', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='EUR', max_digits=10, verbose_name='taxes allocated to transaction')),
                ('cashflow_currency', djmoney.models.fields.CurrencyField(choices=[('EUR', 'Euro'), ('USD', 'US Dollar')], default='EUR', editable=False, max_length=3)),
                ('cashflow', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0.0'), default_currency='EUR', max_digits=10, verbose_name='cashflow during transaction (Neg.=Outgoing)')),
                ('num_transacted', models.DecimalField(decimal_places=5, default=0, max_digits=13, verbose_name='number of securities exchanged (Neg.=Sold)')),
                ('modifiedDate', models.DateField(db_index=True, verbose_name='last modified date')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='returns.Account')),
                ('owner', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('security', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='returns.Security')),
            ],
            managers=[
                ('thobjects2', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='histvaluation',
            name='security',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='returns.Security'),
        ),
    ]
