# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-26 20:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='name of account')),
            ],
        ),
        migrations.CreateModel(
            name='Security',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='name of security')),
                ('descrip', models.CharField(max_length=400, verbose_name='detailed description')),
                ('mark_to_market', models.BooleanField(default=False, verbose_name='True if security priced to market')),
                ('accumulate_interest', models.BooleanField(default=False, verbose_name='True if interest accumulates (e.g. savings accounts)')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='transaction date')),
                ('kind', models.CharField(choices=[('SE', 'SE'), ('BU', 'BU'), ('IN', 'IN'), ('DIV', 'DI')], default='SE', max_length=2, verbose_name='kind of transaction')),
                ('expense', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='expenses allocated to transaction')),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='taxes allocated to transaction')),
                ('cashflow', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='cashflow during transaction (Neg.=Outgoing)')),
                ('num_transacted', models.DecimalField(decimal_places=5, max_digits=13, verbose_name='number of securities exchanged (Neg.=Sold)')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='returns.Account')),
                ('security', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='returns.Security')),
            ],
        ),
    ]
