# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-02 19:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('returns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='security',
            name='url',
            field=models.CharField(default='', max_length=400, verbose_name='URL for pricing info'),
            preserve_default=False,
        ),
    ]
