# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-03 18:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('returns', '0002_security_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='security',
            name='url',
            field=models.CharField(blank=True, default='', max_length=400, verbose_name='URL for pricing info'),
        ),
    ]
