# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-03 18:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('returns', '0003_auto_20160203_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='num_transacted',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=13, verbose_name='number of securities exchanged (Neg.=Sold)'),
        ),
    ]
