# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-03 18:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('returns', '0004_auto_20160203_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='kind',
            field=models.CharField(choices=[('SE', 'SE'), ('BU', 'BU'), ('IN', 'IN'), ('DI', 'DI')], default='SE', max_length=2, verbose_name='kind of transaction'),
        ),
    ]
