# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-08 17:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('returns', '0005_auto_20160203_1942'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistValuation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Valuation date')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valuation')),
                ('security', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='returns.Security')),
            ],
        ),
    ]
