# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-28 16:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('returns', '0006_histvaluation'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='transaction',
            managers=[
                ('thobjects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='security',
            name='kind',
            field=models.CharField(choices=[('TG', 'TG'), ('AK', 'AK'), ('AF', 'AF'), ('BF', 'BF'), ('BD', 'BD'), ('AV', 'AV')], default='AF', max_length=2, verbose_name='kind of security'),
        ),
    ]
