# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-28 16:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('returns', '0007_auto_20160228_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='security',
            name='kind',
            field=models.CharField(choices=[('TG', 'TAGESGELD'), ('AK', 'AKTIE'), ('AF', 'AKTIEN-ETF'), ('BF', 'BONDS-ETF'), ('BD', 'BOND'), ('AV', 'ALTERSVORSORGE')], default='AF', max_length=2, verbose_name='kind of security'),
        ),
    ]
