# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-06 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('returns', '0008_auto_20160228_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='security',
            name='url',
            field=models.URLField(blank=True, default='', max_length=400, verbose_name='URL for pricing info'),
        ),
    ]
