# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-31 19:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('returns', '0010_auto_20160331_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='security',
            name='calc_interest',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Fixed interest rate (%)'),
        ),
    ]
