# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-14 15:08
from __future__ import unicode_literals

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('returns', '0013_auto_20160514_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='security',
            name='currency',
            field=djmoney.models.fields.CurrencyField(default='EUR', max_length=3),
        ),
    ]
