# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-16 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('returns', '0016_inflation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='histvaluation',
            name='date',
            field=models.DateField(db_index=True, verbose_name='Valuation date'),
        ),
    ]
