# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-16 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('returns', '0017_auto_20160516_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateField(db_index=True, verbose_name='transaction date'),
        ),
    ]
