# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-11-01 17:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('returns', '0020_auto_20160818_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='kind',
            field=models.CharField(choices=[('SE', 'Sell'), ('BU', 'Buy'), ('IN', 'Interest'), ('DI', 'Dividend'), ('MA', 'Company Match')], default='SE', max_length=2, verbose_name='kind of transaction'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='owner',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
